### PR TITLE
Add missing $queried_object definition

### PR DESCRIPTION
**Pull request by szepeviktor**
Code from https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/content.php#L9-L13

### All Submissions:

* [ ] Have you followed the [Contributing guidelines](https://github.com/strangerstudios/pmpro-courses/blob/dev/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/pmpro-courses/pulls/) for the same update/change?

### CODE REVIEW

**Comment by mircobabini** [comment]
Why not using `get_the_ID()`?

```php
if( $post_id === null ) {
    $post_id = get_the_ID();
}

if( ! $post_id ) {
     return true;
}

// ...
```

**Comment by szepeviktor** [comment]
I just did the robot-chicken thing: copied and pasted.

I'm not a pmpro user. Please fix it a better way than me!

**Comment by szepeviktor** [comment]
This PR emerged from running @phpstan on this plugin.

**Comment by mircobabini** [comment]
Thanks, pushed the #18 PR which contains a more convenient implementation (to be reviewed).

**Comment by szepeviktor** [comment]
This was an inspirational PR anyway.

**Pull request closed without merging**
